gateways:
  lakehouse:
    connection:
      type: duckdb
      database: ../../../data/tpch.duckdb

default_gateway: lakehouse
disable_anonymized_analytics: true

model_defaults:
  dialect: duckdb
  start: 1992-01-01
  cron: '@daily'
